# -*- coding: utf-8 -*-
"""CSV_Handeler.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nn8Vy4ZPvUuZvcFmnR-yMMhcfyZvgZbd
"""

from google.colab import drive
drive.mount('/content/drive')

bus = []
bus_info = input()
bus_info = bus_info.split()
bus_info[0],bus_